[keyboard]
name = "stingy"
product_name = "stingy"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "rmk"
chip = "nrf52840"

[layout]
rows = 10
cols = 6
layers = 1 
keymap = [
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5"],
        ["Tab", "Q", "W", "E", "R", "T"],
        ["LCtrl", "A", "S", "D", "F", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["_", "_", "MO(1)", "MO(2)", "Space", "LAlt"],
        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Backslash"],
        ["Tab", "Q", "W", "E", "R", "T"],
        ["LCtrl", "A", "S", "D", "F", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["_", "_", "MO(1)", "MO(2)", "Space", "LAlt"]
    ]
]

[ble]
enabled = true
battery_adc_pin = "P0_04" # AIN_2
adc_divider_measured = 2000
adc_divider_total = 2806

[split]
connection = "ble"

[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]

[split.central.matrix]
input_pins = ["P1_11", "P0_10", "P1_13", "P0_09", "P1_06"]
output_pins = ["P0_17", "P0_20", "P0_22", "P0_24", "P1_00", "P0_11"]

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 5
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]


[split.peripheral.matrix]
input_pins = ["P0_17", "P0_20", "P0_22", "P0_24", "P1_00", "P0_11"]
output_pins = ["P0_17", "P0_20", "P0_22", "P0_24", "P1_00", "P0_11"]
