[keyboard]
name = "stingy"
product_name = "stingy"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "rmk"
board = "nice!nano_v2"

[layout]
rows = 10
cols = 6
layers = 1 
keymap = [
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5"],
        ["Tab", "Q", "W", "E", "R", "T"],
        ["LCtrl", "A", "S", "D", "F", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["_", "_", "MO(1)", "MO(2)", "Space", "LAlt"]
        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Backslash"],
        ["Tab", "Q", "W", "E", "R", "T"],
        ["LCtrl", "A", "S", "D", "F", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["_", "_", "MO(1)", "MO(2)", "Space", "LAlt"]
    ]
]

[split]
connection = "ble"

[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0
layers = 1 

[split.central.matrix]
input_pins = ["P0_9", "P0_10", "P0_07", "P1_02","P1_01"]
output_pins = ["P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11"]
