[keyboard]
name = "stingy"
product_name = "stingy"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "rmk"
board = "nice!nano_v2"

[layout]
rows = 10
cols = 6
layers = 1 
keymap = [
    [
        ["A", "B", "C"],
        ["Kc1", "Kc2", "Kc3"],
        ["LCtrl", "MO(1)", "LShift"],
        ["OSL(1)", "LT(2, Kc9)", "LM(1, LShift | LGui)"]
    ]
]

[split]
connection = "ble"

[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0
layers = 1 

[split.central.matrix]
input_pins = ["P0_9", "P0_10", "P0_07", "P1_02","P1_01"]
output_pins = ["P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11"]
